import { lazy, type ComponentType, type LazyExoticComponent } from "react";

export type MadarFamilyId = "foundations" | "controls" | "surfaces" | "shells" | "kinetics";

export interface MadarFamily {
  id: MadarFamilyId;
  label: string;
  labelEn: string;
}

export interface MadarSection {
  id: string;
  title: string;
  titleAr: string;
  family: MadarFamilyId;
  description: string;
  descriptionAr: string;
  tags: string[];
  component: LazyExoticComponent<ComponentType>;
}

export const madarFamilies: MadarFamily[] = [
  { id: "foundations", label: "الأسس", labelEn: "Foundations" },
  { id: "controls", label: "التحكّم والمدخلات", labelEn: "Controls & Inputs" },
  { id: "surfaces", label: "الأسطح والمحتوى", labelEn: "Surfaces & Content" },
  { id: "shells", label: "الأصداف والصفحات", labelEn: "Shells & Pages" },
  { id: "kinetics", label: "الحركة والفيزياء", labelEn: "Motion & Physics" },
];

const load = (name: string, importer: () => Promise<Record<string, ComponentType>>) =>
  lazy(async () => ({ default: (await importer())[name] }));

export const madarSections: MadarSection[] = [
  {
    id: "madar-color-tokens",
    title: "Color Tokens",
    titleAr: "توكنز اللون",
    family: "foundations",
    description: "Every semantic color role shown across the active theme pack.",
    descriptionAr: "كل دور لوني دلالي معروضًا ضمن حزمة الثيم الفعّالة.",
    tags: ["tokens", "color", "theme", "توكنز", "ألوان"],
    component: load("ColorTokens", () => import("./showcase/sections/ColorTokens")),
  },
  {
    id: "madar-typography",
    title: "Typography",
    titleAr: "الخطوط",
    family: "foundations",
    description: "The bilingual type scale and the Arabic and Latin pairing rules.",
    descriptionAr: "سلّم الخط الثنائي وقواعد التزاوج بين العربي واللاتيني.",
    tags: ["type", "scale", "arabic", "خط", "هرمية"],
    component: load("Typography", () => import("./showcase/sections/Typography")),
  },
  {
    id: "madar-icon-lab",
    title: "Icon Lab",
    titleAr: "مختبر الأيقونات",
    family: "foundations",
    description: "Self-drawing icons, orbit rings, clusters, and animated state glyphs.",
    descriptionAr: "أيقونات ترسم نفسها، حلقات مدارية، عناقيد، ورموز حالة متحركة.",
    tags: ["icons", "svg", "ritual", "أيقونات"],
    component: load("IconLab", () => import("./showcase/sections/IconLab")),
  },
  {
    id: "madar-soft-vocabulary",
    title: "Soft Vocabulary",
    titleAr: "المفردات الناعمة",
    family: "foundations",
    description: "Squircle tiles, specular orbs, burst seals, and the soft hue set.",
    descriptionAr: "مربّعات دائرية، كرات لامعة، أختام متفجّرة، ومجموعة الألوان الناعمة.",
    tags: ["soft", "squircle", "orb", "ناعم"],
    component: load("SoftVocabulary", () => import("./showcase/sections/SoftVocabulary")),
  },

  {
    id: "madar-buttons",
    title: "Buttons",
    titleAr: "الأزرار",
    family: "controls",
    description: "One ink primary per view, with sizes, states, and the single allowed gradient.",
    descriptionAr: "أساسي حبري واحد لكل شاشة، مع الأحجام والحالات والتدرّج المسموح مرة واحدة.",
    tags: ["button", "primary", "states", "أزرار"],
    component: load("Buttons", () => import("./showcase/sections/Buttons")),
  },
  {
    id: "madar-inputs",
    title: "Inputs",
    titleAr: "المدخلات",
    family: "controls",
    description: "Fields, selects, toggles, and the focus contract shared by every control.",
    descriptionAr: "الحقول والقوائم والمفاتيح، وعقد التركيز المشترك بين كل الضوابط.",
    tags: ["input", "field", "focus", "مدخلات"],
    component: load("Inputs", () => import("./showcase/sections/Inputs")),
  },
  {
    id: "madar-flow-forms",
    title: "Flow Forms",
    titleAr: "نماذج التدفّق",
    family: "controls",
    description: "Steppers, type pickers, number fields, autocomplete, and unsaved-change bars.",
    descriptionAr: "خطوات ومنتقيات نوع وحقول رقمية وإكمال تلقائي وشريط تغييرات غير محفوظة.",
    tags: ["form", "stepper", "wizard", "نموذج"],
    component: load("FlowForms", () => import("./showcase/sections/FlowForms")),
  },
  {
    id: "madar-essentials",
    title: "Essentials",
    titleAr: "الأساسيات",
    family: "controls",
    description: "Data table, drawer, toast, dropzone, empty state, banner, and range slider.",
    descriptionAr: "جدول بيانات ودرج وإشعار ومنطقة إفلات وحالة فراغ ولافتة ومنزلق نطاق.",
    tags: ["table", "drawer", "toast", "أساسيات"],
    component: load("Essentials", () => import("./showcase/sections/Essentials")),
  },
  {
    id: "madar-data-collections",
    title: "Data Collections",
    titleAr: "مجموعات البيانات",
    family: "controls",
    description: "Tabs, accordion, pagination, kanban, calendar, tree view, and tag input.",
    descriptionAr: "تبويبات وأكورديون وترقيم وكانبان وتقويم وشجرة وإدخال وسوم.",
    tags: ["tabs", "kanban", "calendar", "مجموعات"],
    component: load("DataCollections", () => import("./showcase/sections/DataCollections")),
  },
  {
    id: "madar-text-lists",
    title: "Text & Lists",
    titleAr: "النص والقوائم",
    family: "controls",
    description: "Kinetic headlines, gradient text, list boxes, and activity dropdowns.",
    descriptionAr: "عناوين حركية ونص متدرّج وصناديق قوائم وقوائم نشاط منسدلة.",
    tags: ["text", "list", "dropdown", "نص", "قوائم"],
    component: load("TextLists", () => import("./showcase/sections/TextLists")),
  },
  {
    id: "madar-upload",
    title: "Upload",
    titleAr: "الرفع",
    family: "controls",
    description: "A destination that opens for what lands in it, with per-file state, cancel, and retry.",
    descriptionAr: "وجهة تفتح غطاءها لما يهبط فيها، وحالة لكل ملف مع إلغاء وإعادة محاولة.",
    tags: ["upload", "file", "progress", "رفع", "ملفات"],
    component: load("Upload", () => import("./showcase/sections/Upload")),
  },

  {
    id: "madar-cards",
    title: "Cards",
    titleAr: "البطاقات",
    family: "surfaces",
    description: "The base card grammar: elevation, inset, media, and action placement.",
    descriptionAr: "قواعد البطاقة الأساسية: الارتفاع والحشو والوسائط وموضع الإجراء.",
    tags: ["card", "elevation", "بطاقة"],
    component: load("Cards", () => import("./showcase/sections/Cards")),
  },
  {
    id: "madar-signature-cards",
    title: "Signature Cards",
    titleAr: "البطاقات المميّزة",
    family: "surfaces",
    description: "Blueprint, aperture, breaker, meter dial, tilted stack, and folder cards.",
    descriptionAr: "بطاقات المخطط والعدسة والقاطع وقرص القياس والمكدّس المائل والمجلّد.",
    tags: ["signature", "hero card", "بطاقات"],
    component: load("SignatureCards", () => import("./showcase/sections/SignatureCards")),
  },
  {
    id: "madar-overlays",
    title: "Overlays",
    titleAr: "الطبقات المنبثقة",
    family: "surfaces",
    description: "Popover, tooltip, dropdown, alert dialog, welcome modal, and message dock.",
    descriptionAr: "منبثق وتلميح وقائمة منسدلة وحوار تنبيه ونافذة ترحيب ورصيف رسائل.",
    tags: ["modal", "popover", "dialog", "منبثق"],
    component: load("Overlays", () => import("./showcase/sections/Overlays")),
  },
  {
    id: "madar-data-display",
    title: "Data Display",
    titleAr: "عرض البيانات",
    family: "surfaces",
    description: "Donuts, gauges, heatmaps, rings, sparklines, and log tables.",
    descriptionAr: "دوائر ومقاييس وخرائط حرارية وحلقات ومخططات مصغّرة وجداول سجلّات.",
    tags: ["chart", "gauge", "dataviz", "بيانات"],
    component: load("DataDisplay", () => import("./showcase/sections/DataDisplay")),
  },
  {
    id: "madar-energy",
    title: "Energy",
    titleAr: "الطاقة",
    family: "surfaces",
    description: "A meter read as an instrument, consumption against its own normal, and the tariff ladder.",
    descriptionAr: "عدّاد يُقرأ كجهاز، واستهلاك مقابل معتاده، وسُلّم الشرائح.",
    tags: ["energy", "meter", "kwh", "tariff", "طاقة", "عدّاد", "استهلاك"],
    component: load("Energy", () => import("./showcase/sections/Energy")),
  },
  {
    id: "madar-library-vault",
    title: "Library Vault",
    titleAr: "خزانة المكتبة",
    family: "surfaces",
    description: "The full export map of the library, grouped by source file.",
    descriptionAr: "خريطة التصدير الكاملة للمكتبة، مجمّعة حسب ملف المصدر.",
    tags: ["index", "exports", "map", "خزانة"],
    component: load("LibraryVault", () => import("./showcase/sections/LibraryVault")),
  },
  {
    id: "madar-pattern-atlas",
    title: "Pattern Atlas",
    titleAr: "أطلس الأنماط",
    family: "surfaces",
    description: "The merged pattern compendium drawn from every imported source library.",
    descriptionAr: "موسوعة الأنماط المدموجة من كل مكتبة مصدر مستوردة.",
    tags: ["atlas", "patterns", "أطلس"],
    component: load("PatternAtlas", () => import("./showcase/sections/PatternAtlas")),
  },
  {
    id: "madar-pattern-bank",
    title: "Pattern Bank",
    titleAr: "بنك الأنماط",
    family: "surfaces",
    description: "Reusable content blocks: pricing, bento, masonry, checklists, and footers.",
    descriptionAr: "كتل محتوى قابلة لإعادة الاستخدام: التسعير وبنتو والماسونري وقوائم المهام والتذييل.",
    tags: ["bento", "pricing", "blocks", "بنك"],
    component: load("PatternBank", () => import("./showcase/sections/PatternBank")),
  },
  {
    id: "madar-atelier",
    title: "Atelier",
    titleAr: "الأتيليه",
    family: "surfaces",
    description: "The editorial tier: bezel cards, magnetic CTAs, specular surfaces, display serif.",
    descriptionAr: "الطبقة التحريرية: بطاقات مؤطّرة ونداءات مغناطيسية وأسطح لامعة وخط عرض.",
    tags: ["editorial", "luxury", "bezel", "أتيليه"],
    component: load("Atelier", () => import("./showcase/sections/Atelier")),
  },
  {
    id: "madar-trends-2026",
    title: "Trends 2026",
    titleAr: "اتجاهات 2026",
    family: "surfaces",
    description: "Progressive blur, liquid glass, anticipatory dashboards, and prompt canvases.",
    descriptionAr: "ضبابية تدريجية وزجاج سائل ولوحات استباقية ومساحات أوامر.",
    tags: ["glass", "ai", "trends", "اتجاهات"],
    component: load("Trends2026", () => import("./showcase/sections/Trends2026")),
  },

  {
    id: "madar-hero",
    title: "Hero Showpiece",
    titleAr: "الواجهة الرئيسة",
    family: "shells",
    description: "The aurora glass hero with nested bezels and a z-axis panel cascade.",
    descriptionAr: "واجهة الزجاج الشفقي بإطارات متداخلة وتتابع ألواح على المحور العمقي.",
    tags: ["hero", "glass", "aurora", "واجهة"],
    component: load("Hero", () => import("./showcase/sections/Hero")),
  },
  {
    id: "madar-hero-layouts",
    title: "Hero Layouts",
    titleAr: "تخطيطات الواجهة",
    family: "shells",
    description: "Split stats, product, immersive, display word, and gallery scatter heroes.",
    descriptionAr: "واجهات الإحصاءات المقسومة والمنتج والانغماس وكلمة العرض والمعرض المبعثر.",
    tags: ["hero", "landing", "layout", "تخطيط"],
    component: load("HeroLayouts", () => import("./showcase/sections/HeroLayouts")),
  },
  {
    id: "madar-navigation",
    title: "Navigation",
    titleAr: "التنقّل",
    family: "shells",
    description: "Sidebar, tabs, dock, side rail, breadcrumb, and progressive navbar.",
    descriptionAr: "شريط جانبي وتبويبات ورصيف وسكة ومسار تنقّل وشريط علوي متدرّج.",
    tags: ["nav", "sidebar", "dock", "تنقّل"],
    component: load("Navigation", () => import("./showcase/sections/Navigation")),
  },
  {
    id: "madar-admin-access",
    title: "Admin Access",
    titleAr: "صلاحيات الإدارة",
    family: "shells",
    description: "A complete admin page: shell, permission matrix, member table, and audit log.",
    descriptionAr: "صفحة إدارة كاملة: صدفة ومصفوفة صلاحيات وجدول أعضاء وسجل تدقيق.",
    tags: ["admin", "permissions", "audit", "إدارة"],
    component: load("AdminAccess", () => import("./showcase/sections/AdminAccess")),
  },

  {
    id: "madar-motion",
    title: "Motion",
    titleAr: "الحركة",
    family: "kinetics",
    description: "The curve set and the entrance, state, and exit vocabulary built on it.",
    descriptionAr: "مجموعة المنحنيات ومفردات الدخول والحالة والخروج المبنية عليها.",
    tags: ["motion", "easing", "spring", "حركة"],
    component: load("Motion", () => import("./showcase/sections/Motion")),
  },
  {
    id: "madar-physics-lab",
    title: "Physics Lab",
    titleAr: "مختبر الفيزياء",
    family: "kinetics",
    description: "Magnetic buttons, hold to confirm, slide to unlock, scrubbers, and reordering.",
    descriptionAr: "أزرار مغناطيسية وتأكيد بالضغط المستمر وسحب للفتح ومقابض تمرير وإعادة ترتيب.",
    tags: ["physics", "drag", "haptic", "فيزياء"],
    component: load("PhysicsLab", () => import("./showcase/sections/PhysicsLab")),
  },
  {
    id: "madar-interaction-lab",
    title: "Interaction Lab",
    titleAr: "مختبر التفاعل",
    family: "kinetics",
    description: "The hover, press, and focus contract applied across control families.",
    descriptionAr: "عقد التمرير والضغط والتركيز مطبّقًا على عائلات الضوابط.",
    tags: ["hover", "press", "focus", "تفاعل"],
    component: load("InteractionLab", () => import("./showcase/sections/InteractionLab")),
  },
  {
    id: "madar-interaction-bank",
    title: "Interaction Bank",
    titleAr: "بنك التفاعلات",
    family: "kinetics",
    description: "The flow bank imported from the 21st.dev interaction list.",
    descriptionAr: "بنك التدفّقات المستورد من قائمة تفاعلات 21st.dev.",
    tags: ["interactions", "flows", "بنك"],
    component: load("InteractionBank", () => import("./showcase/sections/InteractionBank")),
  },
  {
    id: "madar-kinetics-bank",
    title: "Kinetics Bank",
    titleAr: "بنك الحركيات",
    family: "kinetics",
    description: "The spring interaction catalog, each entry with its own curve and trigger.",
    descriptionAr: "كتالوج التفاعلات الزنبركية، لكل مدخل منحناه ومحفّزه.",
    tags: ["kinetics", "spring", "حركيات"],
    component: load("KineticsBank", () => import("./showcase/sections/KineticsBank")),
  },
  {
    id: "madar-consequence",
    title: "Consequence",
    titleAr: "الأثر",
    family: "kinetics",
    description: "Controls that show their own outcome: shredding, printing, stretching, filling.",
    descriptionAr: "ضوابط تُظهر أثرها بنفسها: إتلاف وطباعة ومطّ وامتلاء.",
    tags: ["feedback", "destructive", "progress", "أثر", "تغذية راجعة"],
    component: load("Consequence", () => import("./showcase/sections/Consequence")),
  },
  {
    id: "madar-kinetics-99",
    title: "Kinetics 99",
    titleAr: "حركيات 99",
    family: "kinetics",
    description: "The completion set: ripples, meters, loaders, glitches, folds, and 3D flips.",
    descriptionAr: "مجموعة الإكمال: تموّجات ومقاييس ومحمّلات وتشويش وطيّات وقلبات ثلاثية الأبعاد.",
    tags: ["kinetics", "loader", "3d", "حركيات"],
    component: load("Kinetics99", () => import("./showcase/sections/Kinetics99")),
  },
];
